site_name: Cartobat Documentation
site_url: https://cartodoc.com
theme:
    name: readthedocs
nav:
    - Home: index.md
    - Data Gathering: Data_Gathering.md
    - Data Pre-Processing: Data_Pre-Processing.md
plugins:
  - plotly

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: plotly
          class: mkdocs-plotly
          format: !!python/name:mkdocs_plotly_plugin.fences.fence_plotly